<?php

namespace Tests\Feature;

use App\Billing\FakePaymentGateway;
use App\Billing\PaymentGateway;
use App\Models\Concert;
use Faker\Provider\Payment;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PurchaseTicketsTest extends TestCase
{
    use DatabaseMigrations;

protected function setUp(): void
{
    parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentGateway = new FakePaymentGateway();
        $this->app->instance(PaymentGateway::class, $this->paymentGateway);
}


    /**
     * @test
     */
    public function costumer_can_purchase_concert_tickets()
    {
//        $this->withoutExceptionHandling();

//        $paymentGateway = new FakePaymentGateway();
//        $this->app->instance(PaymentGateway::class, $paymentGateway);

        $concert = Concert::factory()->create(['ticket_price' => 3250]);

        $response = $this->json('post', "/concerts/{$concert->id}/orders", [
            'email' => 'john@example.com',
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken()
        ]);

        $response->assertStatus(201);

        $this->assertEquals(9750, $this->paymentGateway->totalCharges());

        $order = $concert->orders()->where('email', 'john@example.com')->first();
        $this->assertNotNull($order);
        $this->assertEquals(3, $order->tickets->count());
    }

    /** @test */
    public function email_is_required_to_purchase_tickets()
    {
        $concert = Concert::factory()->create();

        //Todos os comentários funcionam mas o jeito moderno está descomentado
//        $response = $this->json('POST', "/concerts/$concert->id/orders", [
        $response = $this->postJson("/concerts/$concert->id/orders", [
            'ticket_quantity' => 3,
            'payment_token' => $this->paymentGateway->getValidTestToken()
        ]);

        $response->assertStatus(422);
//        $this->assertArrayHasKey('email', $response->decodeResponseJson()['errors']);
        $response->assertInvalid('email');
    }
}
